---
mnt_bucket: "MY_BUCKET_NAME"
aws_credential:
  aws_accesskey_id: "xxxxxxxxxxxxxxxxxxxx"
  aws_secret_accesskey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
smb:
  user: "cassys"
  password: "xxxxxxxx"
dhcpcd:
  ip: "192.168.50.110/24"
  router_ip: "192.168.50.1"